version: 0.2

phases:
  install:
    commands:
      - echo Installing AWS CLI...
      - yum update -y
      - yum install -y awscli
  build:
    commands:
      - echo Validating CloudFormation templates...
      - aws cloudformation validate-template --template-body file://glue-job.yaml
