version: 0.2

phases:
  install:
    commands:
      - echo Installing AWS CLI...
      - yum update -y
      - yum install -y awscli
  build:
    commands:
      - echo Validating IAM policies...
      - aws cloudformation validate-template --template-body file://iam-policies.yml
      - echo Validating CloudFormation templates...
      - aws cloudformation validate-template --template-body file://glue-job.yml

artifacts:
  files:
    - iam-policies.yml
    - glue-job.yml
