Resources:
  GlueJobRole:
    Type: "AWS::IAM::Role"
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "glue.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      RoleName: "DemoGitOpsGlueJobRole"

  GlueJobPolicy:
    Type: "AWS::IAM::Policy"
    Properties: 
      PolicyName: "demo-gitops-glue-job-policy"
      PolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Action: 
              - "s3:PutObject"
              - "s3:GetObject"
              - "glue:StartJobRun"
            Resource: "*"
      Roles: 
        - 
          Ref: "GlueJobRole"
